routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'MovieController@index');

/* 
*	Route::get('/', function () {
*     return view('home');
* });
*/

Route::resource('/movies', 'MovieController');

Route::get('/formos', 'FormController@index');
Route::post('/formos', 'FormController@displayRequest');

Route::resource('/user', 'UserController');

Route::get('/home', 'HomeController@index');

Auth::routes();

app/Movie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    protected $fillable = [
    	'title',
    	'duration',
    	'year',
    	'image',
    	'description'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use App\Http\Requests;

class FormController extends Controller {

	public function index(){

		$errorMessages = [];

		return view('form', compact('errorMessages'));
	}

	public function displayRequest(Request $request) {
		// var_dump($request->request);

		$rules = array(
				'name' => 'required',
				'email' => 'required|email',
				'email-confirm' => 'required|email|same:email'
			);

		$messages = array(
			'required' => 'Laukelis :attribute turi buti uzpildytas',
			'same' => ':others turi sutapti',
			'email' => 'cia ne emailas laukelyje: :attribute'
			);

		$validator = Validator::make($request->all(), $rules, $messages);
		$errorMessages = [];

		if($validator->passes()) {
			echo "viskas gerai";
		} else {
			$errorMessages = $validator->messages();
		}

		return view('form', compact('errorMessages'));
	}
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use Auth;

class MovieController extends Controller
{
    public function __construct() {
        $this->middleware('auth', ['only' => 'create']);
        // $this->middleware('auth', ['except' => 'index', 'show']);
    }




    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movies = \App\Movie::all();


        return view('movies.index', compact('movies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('movies.create');
        // if(\Auth::guest()) {
        //     return redirect("/login");
        // } else {
        //     return view('movies.create');
        // }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $movie = new \App\Movie();
        $movie->title = $request->title;
        $movie->duration = $request->duration;
        $movie->year = $request->year;
        $movie->image = $request->image;
        $movie->description = $request->description;

        $movie->save();

        // Issaugojimas v2
        // $success = \App\Movie::create($request->all());

        return redirect()->route('movies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $movie = \App\Movie::find($id);

        return view('movies.show', compact('movie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $movie = \App\Movie::find($id);
        if(Auth::guest()) {
            return redirect("/login");
        } else {
            $movie = \App\Movie::find($id);
            return view('movies.create', compact('movie'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \App\Movie::find($id)->update($request->all());

        return redirect()->route('movies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Movie::find($id)->delete();

        return redirect()->route('movies.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use Auth;


class UserController extends Controller
{

    public function __construct() {
        $this->middleware(function($request, $next) {
            if(\Auth::guest()
                ||
                (!\Auth::guest() && \Auth::user()->is_admin == 0)) {
                return redirect()->route('login');
            }
            return $next($request);
        });
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = \App\User::all();

        return view('user.index', compact('user'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('user.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $success = \App\User::create($request->all());
        return redirect()->route('user.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = \App\User::find($id);

        return view('user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = \App\User::find($id);
        return view('user.create', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /**
        * $data = $request->all();
        * $data['password'] = \Hash::make($request->password);
        * uzhashina pasworda
        */

        \App\User::find($id)->update($request->all());
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\User::find($id)->delete();

        return redirect()->route('user.index');
    }
}

resources/views/form.blade.php
@extends("layout.main")

@section("content")

@if(count($errorMessages)>0)
	<h3>Yra klaidu</h3>
	<ul>
		@foreach($errorMessages->all() as $error)
		<li>{{$error}}</li>
		@endforeach
	</ul>
@endif


<h2>Form :)</h2>


{!! Form::open(['url' => '/formos', 'method'=>"POST"]) !!}

	{{Form::label('name', 'Name')}}
	{{Form::text('name', '', ['class'=>'form-control'])}}

	{{Form::label('email', 'E-Mail Address')}}
    {{Form::text('email','example@gmail.com', ['class'=>'form-control'])}}

    {{Form::label('email-confirm', 'confirm E-Mail Address')}}
    {{Form::text('email-confirm','example@gmail.com', ['class'=>'form-control'])}}

    {{Form::submit('Enter')}}
    
{!! Form::close() !!}

@endsection

resources/views/home.blade.php
@extends('layout.main')
@extends('layouts.app')



@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                	@if(Auth::guest())
                		You are guest
                	@else
                    	You are logged in!
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout/footer.blade.php
</body>
</html>

resources/views/layout/header.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
	<title>Movies DB</title>
</head>
<body>
	<nav class="navbar navbar-default">
  		<div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
	      		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
	      		</button>
	      		<a class="navbar-brand" href="#">Movies database</a>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      		<ul class="nav navbar-nav">
	      			<li class="{{ Route::is('movies.index') ? 'active': '' }}">
	      				<a href="{{ route('movies.index') }}">Movies</a>
	      			</li>
	      			@if(\Auth::guest() || (!\Auth::guest() && \Auth::user()->is_admin == 0))
	      			@else
	      			<li class="{{ Route::is('movies.create') ? 'active': '' }}">
	      				<a href="{{ route('movies.create') }}">Create movies</a>
	      			</li>
	      			<li class="{{ Route::is('user.index') ? 'active': '' }}">
	      				<a href="{{ route('user.index') }}">Users</a>
	      			</li>
	      			@endif
	      		</ul>
	      		<!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
	      	</div>

	    </div>  	
    </nav>

resources/views/layout/main.blade.php
@include("layout.header")

@yield("content")

@include("layout.footer")

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/movies/create.blade.php
@extends("layout.main")

@section("content")

<h3>Add Movie</h3>



	@if(isset($movie))
	{{Form::open(['route' => ['movies.update', $movie->id], 'method' => 'POST'])}}
	{{Form::hidden('_method', 'PUT')}}
	@else
	{{Form::open(['route' => 'movies.store', 'method' => 'POST'])}}
	@endif

	{{ csrf_field() }}

	{{Form::label('title', 'Title:')}}
	@if(isset($movie))
	{{Form::text('title', ($movie['title']), ['class'=>'form-control'])}}
	@else
	{{Form::text('title', '', ['class'=>'form-control'])}}
	@endif

	{{Form::label('duration', 'Duration:')}}
	@if(isset($movie))
	{{Form::text('duration', ($movie['duration']), ['class'=>'form-control'])}}
	@else
	{{Form::text('duration', '', ['class'=>'form-control'])}}
	@endif

	{{Form::label('year', 'Year:')}}
	@if(isset($movie))
	{{Form::text('year', ($movie['year']), ['class'=>'form-control'])}}
	@else
	{{Form::text('year', '', ['class'=>'form-control'])}}
	@endif

	{{Form::label('image', 'Image URL:')}}
	@if(isset($movie))
	{{Form::text('image', ($movie['image']), ['class'=>'form-control'])}}
	@else
	{{Form::text('image', '', ['class'=>'form-control'])}}
	@endif

	{{Form::label('description', 'Description:')}}
	@if(isset($movie))
	{{Form::textarea('description', ($movie['description']), ['class'=>'form-control'])}}
	@else
	{{Form::textarea('description', '', ['class'=>'form-control'])}}
	@endif

    {{Form::submit('Save', ['class' => 'btn btn-primary'])}}


{!! Form::close() !!}



    @if(isset($movie))
    {{Form::open(['route' => ['movies.destroy', $movie->id], 'method' => 'POST'])}}
    {{Form::hidden('_method', 'DELETE')}}


	{{ csrf_field() }}

	{{Form::submit('Delete', ['class' => 'btn btn-danger'])}}
	@endif
    
{!! Form::close() !!}


@endsection


{{--
 @if(isset($movie))
}
}
<form class="container" action="{{ route('movies.update', $movie->id) }}" method="POST">
<input type="hidden" name="_method" value="PUT">
@else
<form action="{{ route('movies.store') }}" method="POST">
@endif




	{{ csrf_field() }}

	<label>Title:</label>
	@if(isset($movie))
	<input  value="{{ $movie['title'] }}" class="form-control" type="text" name="title">
	@else
	<input class="form-control" type="text" name="title">
	@endif

	<label>Duration:</label>
	@if(isset($movie))
	<input  value="{{ $movie['duration'] }}" class="form-control" type="number" name="duration">
	@else
	<input  class="form-control" type="number" name="duration">
	@endif

	<label>Year:</label>
	@if(isset($movie))
	<input  value="{{ $movie['year'] }}" class="form-control" type="text" name="year">
	@else
	<input  class="form-control" type="text" name="year">
	@endif

	<label>Image URL:</label>
	@if(isset($movie))
	<input  value="{{ $movie['image'] }}" class="form-control" type="text" name="image">
	@else
	<input  class="form-control" type="text" name="image">
	@endif

	<label>Description:</label>
	@if(isset($movie))
	<textarea class="form-control" name="description" cols="30" rows="10">{{
	$movie['description'] }}</textarea>
	@else
	<textarea class="form-control" name="description" cols="30" rows="10"></textarea>
	@endif
	
	<input class="btn btn-primary" type="submit" name="Save">
</form>

@if(isset($movie))
<form action="{{ route('movies.destroy', $movie->id) }}" method="POST">
<input type="hidden" name="_method" value="DELETE">


{{ csrf_field() }}

<button type="submit" class="btn btn-danger">Delete</button>
</form>
@endif


{!! Form::open(['url' => '/formos', 'method'=>"GET"]) !!}
    {{Form::text('email','example@gmail.com', ['class'=>'awesome', 'id'=>'geras'])}}
    {{Form::submit('Enter')}}
    {{Form::text('username','username-example')}}
{!! Form::close() !!}
--}}
 

resources/views/movies/index.blade.php
@extends("layout.main")

@section("content")


<ul>
@foreach($movies as $movie)

	<li>{{ $movie['title'] }}</li>
	<li>{{ $movie['description'] }}</li>
	<li> <a href="{{ route('movies.show', $movie->id) }}"> <img src="{{ $movie['image'] }}"></a></li>
	<li>Year {{ $movie['year'] }}</li>
	<li>{{ $movie['duration'] }} min.</li>
	@if(\Auth::guest() || (!\Auth::guest() && \Auth::user()->is_admin == 0))
	@else
	<a href="{{ route('movies.edit', $movie->id) }}">Edit</a>
	@endif
	<hr>

@endforeach
</ul>

@endsection

resources/views/movies/show.blade.php
@extends("layout.main")

@section("content")

	<ul>

	<li>{{ $movie['title'] }}</li>
	<li>{{ $movie['description'] }}</li>
	<li><img src="{{ $movie->image }}"></li>
	<li>{{ $movie['year'] }}</li>
	<li>{{ $movie['duration'] }}</li>
	@if(\Auth::guest() || (!\Auth::guest() && \Auth::user()->is_admin == 0))
	@else
	<a href="{{ route('movies.edit', $movie->id) }}">Edit</a>
	@endif
	<hr>

</ul>

@endsection

resources/views/user/create.blade.php
@extends("layout.main")

@section("content")



	@if(isset($user))
	{{Form::open(['route' => ['user.update', $user->id], 'method' => 'POST'])}}
	{{Form::hidden('_method', 'PUT')}}
	@else
	{{Form::open(['route' => 'user.store', 'method' => 'POST'])}}
	@endif

	{{ csrf_field() }}

	{{Form::label('name', 'User:')}}
	@if(isset($user))
	{{Form::text('name', ($user['name']), ['class'=>'form-control'])}}
	@else
	{{Form::text('name', '', ['class'=>'form-control'])}}
	@endif

	{{Form::label('email', 'Email:')}}
	@if(isset($user))
	{{Form::text('email', ($user['email']), ['class'=>'form-control'])}}
	@else
	{{Form::text('email', '', ['class'=>'form-control'])}}
	@endif




	@if(isset($user))
	{{Form::label('is_admin', "Is Admin?")}}
	{{Form::hidden('is_admin', 0 )}}
	{{Form::checkbox('is_admin', 1 , $user->is_admin)}}
	@else

	@endif

	

    {{Form::submit('Save', ['class' => 'btn btn-primary'])}}

    


{!! Form::close() !!}


	@if(isset($user))
    {{Form::open(['route' => ['user.destroy', $user->id], 'method' => 'POST'])}}
    {{Form::hidden('_method', 'DELETE')}}


	{{ csrf_field() }}

	{{Form::submit('Delete', ['class' => 'btn btn-danger'])}}
	@endif
    
    
{!! Form::close() !!}

@endsection

resources/views/user/index.blade.php
@extends("layout.main")

@section("content")
<div class="container">
	<h1>Vartotojai</h1>

	
		<div class="col-md-12">
			
		</div>
	<div class="col-md-10 col-md-offset-1">

            <div class="panel panel-default panel-table">
              <div class="panel-heading">
                <div class="row">
                  <div class="col col-xs-6">
                    <h3 class="panel-title">Users</h3>
                  </div>
                </div>
              </div>
              <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                        <th><em class="fa fa-cog"></em></th>
                        <th class="hidden-xs">ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Created at</th>
                    </tr> 
                  </thead>
                  <tbody>
                  	@foreach($user as $user)
                          <tr>
                            <td align="center">
                              <a href="{{ route('user.edit', $user->id) }}" class="btn btn-default"><em class="fa fa-pencil"></em></a>
                              
                              {{Form::open(['route' => ['user.destroy', $user->id], 'method' => 'POST'])}}
							  {{Form::hidden('_method', 'DELETE')}}

								{{ csrf_field() }}

								{{Form::submit('Delete', ['class' => 'btn btn-danger'])}}
							    
								{!! Form::close() !!}

                            </td>
                            <td class="hidden-xs">{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->created_at }}</td>
                          </tr>
					@endforeach

                        </tbody>
                </table>
            </div>
        </div>
	</div>


@endsection